book:
  toc_nb_name: 00.00-Pagina_Inicial.ipynb
  header: "[*Guia de aulas da disciplina de Modelagem Matem√°tica*](https://github.com/rmsrosa/modelagem_matematica) *do* [*IM-UFRJ*](https://www.im.ufrj.br)."
  core_navigators:
    - 00.00-Pagina_Inicial.ipynb
  user: rmsrosa
  repository: modelagem_matematica
  branch: modmat2019p1
  github_nb_dir: aulas
  github_io_slides_dir: aulas
  show_colab: True
  show_binder: True
  show_slides: True
  show_full_entry_in_toc: False
  show_full_entry_in_nav: False